"""empty message

Revision ID: 12649df44009
Revises: bd38504d57d1
Create Date: 2021-07-28 00:45:30.018109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12649df44009'
down_revision = 'bd38504d57d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date', table_name='vital')
    op.drop_index('value', table_name='vital')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('value', 'vital', ['value'], unique=False)
    op.create_index('date', 'vital', ['date'], unique=False)
    # ### end Alembic commands ###
