"""empty message

Revision ID: 55ebfd4a8468
Revises: 12649df44009
Create Date: 2021-07-30 22:48:39.822820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ebfd4a8468'
down_revision = '12649df44009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('dose', table_name='medication')
    op.drop_index('frequency', table_name='medication')
    op.drop_index('reason', table_name='medication')
    op.drop_index('side_effects', table_name='medication')
    op.drop_index('frequency', table_name='symptom')
    op.drop_index('location', table_name='symptom')
    op.drop_index('severity', table_name='symptom')
    op.drop_index('startDate', table_name='symptom')
    op.add_column('symptom_note', sa.Column('severity', sa.Integer(), nullable=False))
    op.drop_index('date', table_name='symptom_note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('date', 'symptom_note', ['date'], unique=False)
    op.drop_column('symptom_note', 'severity')
    op.create_index('startDate', 'symptom', ['startDate'], unique=False)
    op.create_index('severity', 'symptom', ['severity'], unique=False)
    op.create_index('location', 'symptom', ['location'], unique=False)
    op.create_index('frequency', 'symptom', ['frequency'], unique=False)
    op.create_index('side_effects', 'medication', ['side_effects'], unique=False)
    op.create_index('reason', 'medication', ['reason'], unique=False)
    op.create_index('frequency', 'medication', ['frequency'], unique=False)
    op.create_index('dose', 'medication', ['dose'], unique=False)
    # ### end Alembic commands ###
