"""empty message

Revision ID: 61ad08e10069
Revises: 
Create Date: 2021-07-31 20:26:34.049498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ad08e10069'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dose', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('side_effects', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('next_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=False),
    sa.Column('time', sa.String(length=200), nullable=False),
    sa.Column('doctorName', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('doctorName'),
    sa.UniqueConstraint('time')
    )
    op.create_table('symptom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptomName', sa.String(length=120), nullable=False),
    sa.Column('startDate', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('frequency', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vital_name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('symptom_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom_note')
    op.drop_table('vital')
    op.drop_table('symptom')
    op.drop_table('next_visit')
    op.drop_table('medication')
    op.drop_table('user')
    # ### end Alembic commands ###
