"""empty message

Revision ID: 6e5e12932def
Revises: 61ad08e10069
Create Date: 2021-08-03 00:11:52.023126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e5e12932def'
down_revision = '61ad08e10069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('date', table_name='next_visit')
    op.drop_index('doctorName', table_name='next_visit')
    op.drop_index('time', table_name='next_visit')
    op.drop_table('next_visit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('next_visit',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('time', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('doctorName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name='next_visit_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('time', 'next_visit', ['time'], unique=False)
    op.create_index('doctorName', 'next_visit', ['doctorName'], unique=False)
    op.create_index('date', 'next_visit', ['date'], unique=False)
    op.drop_table('all_doctors')
    # ### end Alembic commands ###
