"""empty message

Revision ID: 8b9c005c5d80
Revises: 55ebfd4a8468
Create Date: 2021-07-31 20:19:46.097970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b9c005c5d80'
down_revision = '55ebfd4a8468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('medication_ibfk_1', 'medication', type_='foreignkey')
    op.drop_column('medication', 'username')
    op.alter_column('symptom', 'severity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('symptom', 'location',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('symptom', 'frequency',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('symptom_note', 'severity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('symptom_note', 'note',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symptom_note', 'note',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('symptom_note', 'severity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('symptom', 'frequency',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('symptom', 'location',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('symptom', 'severity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('medication', sa.Column('username', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('medication_ibfk_1', 'medication', 'user', ['username'], ['username'])
    # ### end Alembic commands ###
