"""empty message

Revision ID: daea8d03deb3
Revises: 5b916facda81
Create Date: 2021-07-27 00:38:34.276259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daea8d03deb3'
down_revision = '5b916facda81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dose', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('side_effects', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dose'),
    sa.UniqueConstraint('frequency'),
    sa.UniqueConstraint('reason'),
    sa.UniqueConstraint('side_effects')
    )
    op.create_table('next_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=False),
    sa.Column('time', sa.String(length=200), nullable=False),
    sa.Column('doctorName', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('doctorName'),
    sa.UniqueConstraint('time')
    )
    op.create_table('symptom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptomName', sa.String(length=120), nullable=False),
    sa.Column('startDate', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=2), nullable=False),
    sa.Column('location', sa.String(length=60), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frequency'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('severity'),
    sa.UniqueConstraint('startDate')
    )
    op.create_table('symptom_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=False),
    sa.Column('symptom_id', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.add_column('user', sa.Column('fullname', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('address', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'user', ['fullname'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_unique_constraint(None, 'user', ['address'])
    op.add_column('vital', sa.Column('vitalname', sa.String(length=200), nullable=False))
    op.add_column('vital', sa.Column('date', sa.String(length=200), nullable=False))
    op.add_column('vital', sa.Column('value', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'vital', ['date'])
    op.create_unique_constraint(None, 'vital', ['value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vital', type_='unique')
    op.drop_constraint(None, 'vital', type_='unique')
    op.drop_column('vital', 'value')
    op.drop_column('vital', 'date')
    op.drop_column('vital', 'vitalname')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'fullname')
    op.drop_table('symptom_note')
    op.drop_table('symptom')
    op.drop_table('next_visit')
    op.drop_table('medication')
    # ### end Alembic commands ###
